version: "2"

services:
  grafana:
    image: grafana/grafana:8.1.0
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - ComposeJmeter
    volumes:
      - grafana-volume:/ComposeJmeter
  influxdb:
    image: influxdb:1.8.0
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - ComposeJmeter
    volumes:
      - influxdb-volume:/ComposeJmeter
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_USER=telegraf
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=Welcome1
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    extra_hosts:
     - "influxdb:192.168.1.8"
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    volumes:
     - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - /sys:/rootfs/sys:ro
     - /proc:/rootfs/proc:ro
     - /etc:/rootfs/etc:ro
networks:
  ComposeJmeter:
volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true