name: Test JMeter Action

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: JMeter Test
        uses: Vlad-Kliucharov/JmeterFloodIO-Influx@v1.0
        with:
          test-plan-path: JmeterFloodIO-Influx/SurveyCheck.jmx
          args: "-H 192.168.0.181"
          
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result.jtl
