# This is a workflow to help you run all JMeter scripts with Actions, and save Test Results as artifact

name: jmeter_test_results

# Controls when the workflow will run
on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# env:
#   TEST_NAME: SurveyCheck
#   VUSERS: 15 
#   RAMP_UP: 150
#   DURATION: 100
#   JVM_ARGS: -Xms1g -Xmx2g -Xmx256m
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  action_build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Create image
        run: docker build -t jmeter .

      - name: Create container
        run: docker run -it --name jcont jmeter
        
      - name: create Reports dir
        run: |
          mkdir $GITHUB_WORKSPACE/Reports

      # - name: JMeter Test
      #   run: docker run --name jcont --env jmeter -n -t JmeterFloodIO-Influx/SurveyCheck.jmx -JVUsers=15 -JRamp_Up=$150 -JDuration=15 -l $GITHUB_WORKSPACE/Reports/test.jtl -e -o $GITHUB_WORKSPACE/Reports
      runs:
        using: 'docker'
        image: 'jmeter'
        container: 'jcont'
        args:
        - "-n"
        - "-t"
        - "JmeterFloodIO-Influx/SurveyCheck.jmx"
        - "-l"
        - "result.jtl"

      # - name: Upload JMeter Test Results
      #   uses: actions/upload-artifact@v2.2.4
      #   with:
      #    name: test_results
      #    path: test_report
