name: Test JMeter Action

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
      - uses: actions/checkout@v2

      - name: create Reports dir
        run: |
          mkdir $GITHUB_WORKSPACE/Reports

      - name: JMeter Test
        uses: Vlad-Kliucharov/JmeterFloodIO-Influx@v1.0
        with:
          run: docker run --name jmeter -n -t JmeterFloodIO-Influx/SurveyCheck.jmx -JVUsers=15 -JRamp_Up=$150 -JDuration=15 -l $GITHUB_WORKSPACE/Reports/test.jtl -e -o $GITHUB_WORKSPACE/Reports
          
      - name: Upload Results
        uses: actions/Reports@v1
        with:
          name: jmeter-results
          path: result.jtl
