name: Test JMeter Action

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run JMeter Action on a test
        uses: Vlad-Kliucharov/JmeterFloodIO-Influx@v1.0

        with:
          testFilePath: JmeterFloodIO-Influx/SurveyCheck.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO"

      - uses: actions/upload-artifact@v1
        with:
          name: jmeter-test-results
          path: reports/
