# This is a workflow to help you run all JMeter scripts with Actions, and save Test Results as artifact

name: jmeter_test_results

# Controls when the workflow will run
on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  TEST_NAME: SurveyCheck
  VUSERS: 15 
  RAMP_UP: 150
  DURATION: 100
  JVM_ARGS: -Xms1g -Xmx2g -Xmx256m
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  action_build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Create image
        run: docker build -t jmeter .

      - name: Create container
        run: docker run -t --name jcont jmeter
        
      - name: create Reports dir
        run: |
          mkdir $GITHUB_WORKSPACE/Reports

      - name: Remove exists container
        run: docker rm --force jcont

      - name: JMeter Test
        run: docker run --name jcont --env '$JVM_ARGS' -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE jmeter -n -t $GITHUB_WORKSPACE/$TEST_NAME.jmx -JVUsers=$VUSERS -JRamp_Up=$RAMP_UP -JDuration=$DURATION -l $GITHUB_WORKSPACE/Reports/test.jtl -e -o $GITHUB_WORKSPACE/Reports

      - name: Upload JMeter Test Results
        uses: actions/upload-artifact@v2
        with:
         name: test_results
         path: $GITHUB_WORKSPACE/Reports
